language: python
python:
- '3.6'
install:
- pip install tox-travis
script:
- tox
- python setup.py bdist_wheel sdist
deploy:
  provider: pypi
  user: __token__
  password:
    secure: ET8peAjAF8opUz5XDltbmCE3WCto/76A2ihJxRhE8PD90YrU/kMfhT0mCiYpB31VeNkkEGlaRwL92n9qj0Fdqk/qzpR4dZ0Rn2QR8IR3iKqNmbaA66Q4bSxQdesQQM7sqspv3ZncE/pF+h0lnmICQ7YnnMqNvmHpRX8OYrY52mL5YuXyqobxQPlQpczRtSbLfWJlHbRfMn1NNdclSMR/bKD6TCGrKuXGAs0xXlqyPEbX82W+5uGpOdMnBmrf4R7nkQPcORUtUle8A+BYmF56dy2jUjRDhj1LV+R06qFszjtq2u5PkHJUHEVzjo1xDwX6hZESCE5QXCuCWyLmKAosCKlMlZ0f6qb6SPIyygTlQctBziQXnORSnmOHttk0pjb2wkv4m4IdCVby9zqewsG9iZBirmeK1/wVz7Tx0CsTfYg8EGTsbpGlIcghLZ1W6rUKimw58DV5zmUnVNpQWmSbzxMSsjn4uzedORqYImteB4bI7CZJXPR1CV+XZ361XUwVJDA4dcV0MubWiuQlChixAmFuG4GLKx9unE6qMufhLBwCnZK/eFffMaAbDXTF1z+HexEGGsOXsMzKxwSMUasMNbkiN8fShQi7PlhhUhaA5bTu93eT0DDu/qiTxI0B0CfD3LJV1goQXmA6zCsN9xiuo6eNb47iFp3I7EUnHmYh76A=
  skip_cleanup: true
  on:
    tags: false
  skip_existing: true
